name: Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: false

      - name: Image build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kubernetes-test-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/kubernetes-test-app:latest

      - name: Push and update the ops repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Airaad/argocd-ops.git
          cd argocd-ops/ops
          sed -i 's|image: airaad962/kubernetes-test-app:.*|image: airaad962/kubernetes-test-app:${{ github.sha }}|' manifest1.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "updated image tag to ${{ github.sha }}"
          git push https://${PAT}@github.com/Airaad/argocd-ops.git main
